### ISSUE TITLE
Spotify compability

### ISSUE THREAD

**Issue by Nega-Berk** [ModernFlyouts-Community/ModernFlyouts#1138]
### Description of the new feature / enhancement

Hi. Please add restart in tray menu. Sometimes spotify dissapear or cant work properly. Restart app fixes it.

### Scenario when this would be used?

Restarting spotify or restarting modernlflyouts missing media queue someting.

**Comment by Nega-Berk** [comment]
Done.

**Comment by Poopooracoocoo** [comment]
@Nega-Berk ... that still doesn't reflect your suggestion. Might I suggest renaming it to "Add restart to tray menu"?

**Comment by Nega-Berk** [comment]
Done.
