### ISSUE TITLE
Bug: Volume flyout pops up when changing keyboard layout

### ISSUE THREAD

**Issue by timothymhuang** [ModernFlyouts-Community/ModernFlyouts#584]
**Describe the bug:**
When using the keyboard shortcuts to change the keyboard layout, the modern flyouts volume flyout pops up.

**To Reproduce:**
1. Make sure you have at least two keyboard layouts installed on your computer.
2.  Use (Win + Space), (Ctrl + Shift), or (Shift + Alt) to change the keyboard layout. 
3. Notice how the volume flyout shows, even though the volume isn't changing.

**Screenshots:**

**OS Version:**
 - Windows 10 Version: Windows 10 Pro 20H2

**ModernFlyouts Version:**
 - Version: v0.9.2.0

**Additional context:**

**Comment by occune** [comment]
Can confirm, keyboard layout hotkeys trigger the layout
ModernFlyouts version 0.9.3.0, installed on 19042.928

**Comment by Cyberdroid1** [comment]
@ShankarBUS 
This sounds like a side effect of the method used to fix #4.

**Comment by ShankarBUS** [comment]
Alright

**Comment by yoyrandao** [comment]
Yes, I have the same

**Comment by mhggpo** [comment]
the same

**Comment by Shuna322** [comment]
Same issue

**Comment by PhyX-Meow** [comment]
The following step fix the issue for me:
1. Exit Modern flyouts app.
2. Change some audio volume and then change it back.
3. Restart the app.
Aha, audio flyout will no longer appear when press win+space or so.

**Comment by ShankarBUS** [comment]
MS be like "let's reuse the same window for all things". Why would they even do that? Would it hurt them to make a separate window for language switcher?

Now, my precious hack is obsolete!

**Comment by D1m0n228** [comment]
Can't fix it in any way?

**Comment by ShankarBUS** [comment]
So many complaints....
Hmmmmmmmmmmmmmmm....

Seems like this bug should be looked on ASAP. Hmmmmmmmmmmmmmmm....., ight imma investigate.

**Comment by playday3008** [comment]
Same

**Comment by EvasiveXkiller** [comment]
Pressing the language button on the taskbar brings the volume panel up too

**Comment by ShankarBUS** [comment]
Bruh

**Comment by ShankarBUS** [comment]
So, ummm.... people,
What happened was,......

It was my silly mistake. I have fixed this bug in d9c1b33a51b8dcea36c6cf2d720ca6a0254530c1.

You may expect this fix to be available in the v0.10 release coming later (this month?).

Sorry for the annoyance.

Have a great day! Stay safe!

**Comment by vadrif-draco** [comment]
I'm not sure why this is closed and any other mention of the issue gets marked as a dupe and closed afterwards. The issue still exists!

**Comment by manstheram** [comment]
@vadrif-draco It was theoretically already fixed in a commit - it's just that, a stable version containing that commit has yet to be released.

**Comment by vadrif-draco** [comment]
Is there a way to get the beta version that contains the fix then? It is really annoying and 3 years to release is a very long time :(

**Comment by manstheram** [comment]
I think the beta in this repo has expired but I already made a release in my fork so go use that one https://github.com/manstheram/ModernFlyouts/releases/tag/v0.10.0-beta.4
Install the certificate, before installing the bundle, in the Trusted Root Authority under "Local Machine".
And note: I don't know if the issue has been fixed properly yet, but it should be.
