### ISSUE TITLE
Bug: Doesn't start

### ISSUE THREAD

**Issue by guusbuk** [ModernFlyouts-Community/ModernFlyouts#955]
### ModernFlyouts Version

Latest on the Windows Store.

### Windows version

Windows 11 21H2

### Platform

x64

### Area(s) with issue?

System tray

### Steps to reproduce

Open ModernFlyouts.

### ✔️ Expected Behavior

ModernFlyouts runs and you can open the settings in the taskbar and when using volume+ button I get the Modern Flyout.

### ❌ Actual Behavior

It gets run shortly, then it crashes/stops.
I can see the icon in the taskbar for about 3 seconds, but I can't click on it. When using volume+ I get the normal Windows flyout.

### Additional Context

It was all working well, even on Windows 11 till today. It doesn't work now anymore.

**Comment by FerlixMN** [comment]
i have the same issue

**Comment by BodyLKT** [comment]
Me too. Same issue.

**Comment by Samuel12321** [comment]
we are working on this , should be fixed in 0.11

**Comment by Cyberdroid1** [comment]
Isnt this related to #642?

**Comment by tahayparker** [comment]
any updates? got a new laptop and it just wont start
no icon on taskbar, no icon in tray, just doesn't respond

**Comment by manstheram** [comment]
@tahayparker It was fixed in v10 beta 3.

**Comment by RegorForgot** [comment]
> @tahayparker It was fixed in v10 beta 3.

I am currently still having this problem. The app does not even start up properly, I added a task scheduler instance for it to start up and even then the flyout does not drop. You can access the application settings but the volume flyout isn't shown.

**Comment by RegorForgot** [comment]
> @RegorForgot What Windows version are you on? An insider one?

No, this is a new clean install of windows, version 10.0.22621

**Comment by tahayparker** [comment]
> @tahayparker It was fixed in v10 beta 3.

currently don't have access to this device will test in about 1 month

**Comment by vinceingithub** [comment]
I can't install it on any new devices. It works only on the device that's had it installed for a while.
